### ISSUE TITLE
Did this ever get resolved?

### ISSUE THREAD

**Issue by dtrikannad** [kentcdodds/nonce-hydration-issues#1]
Hi Kent,

Were you able to resolve the "Extra attributes from the server: nonce" issue? I'm running into that now. If you were, could you share how you overcame this warning?

![image](https://github.com/kentcdodds/nonce-hydration-issues/assets/1844616/9aa30635-8f7e-4ce6-ad25-550d2cd4eb92)

Thanks!

Deep

**Comment by kentcdodds** [comment]
Hi @dtrikannad,

Check out how we solve it in the [Epic Stack](https://github.com/epicweb-dev/epic-stack)
